/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;
import java.awt.Color;
import java.util.Vector;
import  javax.swing.*;
import java.sql.*;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dinos
 */
public class ConnectionDB extends javax.swing.JFrame {

    /**
     * Creates new form ConnectionDB
     */
    private Connection connDB;
    public ConnectionDB() {
        initComponents();
        Query1.setToolTipText("Εμφανίζει την μέση εμπιστοσύνη  κάθε borrower");
        Query2.setToolTipText("Εμφανίζει το υπόλοιπο κάθε δανείου ,το ποσό του δάνειου και το ποσό που έχει \n" +
"καταβληθεί.");
       Query3.setToolTipText("Εμφανίζει τους Lenders οι οποίοι έχουν προσφέρει πάνω απ’ το μισό ποσό ενός τουλάχιστον Loan Request και πόσα τέτοια commitments έχουν κάνει.");
       Query4.setToolTipText("Εμφανίζει για κάθε δάνειο,πόσα commitments χρειάστηκαν για  να εγκριθεί.");
       Query5.setToolTipText("Εμφανίζει τα κόκκινα δάνεια.");
       query6.setToolTipText("Εμφανίζει τα δάνεια τα οποία έχουν αποπληρωθεί.");
       Query7.setToolTipText("Εμφανίζει τους borrowers οι οποίοι έχουν πάρει δάνεια συνολικής αξίας μεγαλύτερης των \n" +
"10000 ,σε φθίνουσα σειρά με βάση το συνολικό ποσό.");
       Query8.setToolTipText("Εμφανίζει τα στεγαστικά δάνεια και τον δανειολήπτη.");
       Query9.setToolTipText("Εμφανίζει τα Loan Requests τα οποία έχουν λήξει.");
       Query10.setToolTipText("Εμφανίζει το ποσό που χρειάζεται κάθε Loan request για να εγκριθεί το αντίστοιχο δάνειο.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConnectBtn = new javax.swing.JButton();
        Borrowers = new javax.swing.JButton();
        Lenders = new javax.swing.JButton();
        Inter_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Query1 = new javax.swing.JButton();
        Query2 = new javax.swing.JButton();
        Query10 = new javax.swing.JButton();
        Query9 = new javax.swing.JButton();
        Query3 = new javax.swing.JButton();
        Query8 = new javax.swing.JButton();
        Query5 = new javax.swing.JButton();
        Query4 = new javax.swing.JButton();
        query6 = new javax.swing.JButton();
        Query7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Microloans  Database Management System");

        ConnectBtn.setText("Connect to Microloans");
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });

        Borrowers.setText("Borrowers");
        Borrowers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowersActionPerformed(evt);
            }
        });

        Lenders.setText("Lenders");
        Lenders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LendersActionPerformed(evt);
            }
        });

        Inter_btn.setText("Intermediaries");
        Inter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inter_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Queries");

        Query1.setText("Αvg_Trust");
        Query1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query1ActionPerformed(evt);
            }
        });

        Query2.setText("Loan_Balance");
        Query2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query2ActionPerformed(evt);
            }
        });

        Query10.setText("LoanR_Balance");
        Query10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query10ActionPerformed(evt);
            }
        });

        Query9.setText("LoanR_Rotten");
        Query9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query9ActionPerformed(evt);
            }
        });

        Query3.setText("Ld_amnt>1/2");
        Query3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query3ActionPerformed(evt);
            }
        });

        Query8.setText("Mortgages");
        Query8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query8ActionPerformed(evt);
            }
        });

        Query5.setText("RedLoans");
        Query5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query5ActionPerformed(evt);
            }
        });

        Query4.setText("Comm/Loan");
        Query4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query4ActionPerformed(evt);
            }
        });

        query6.setText("Paid_off_L");
        query6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query6ActionPerformed(evt);
            }
        });

        Query7.setText("BorLoans>1000");
        Query7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query7ActionPerformed(evt);
            }
        });

        jButton1.setText("Loan Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Loans");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Commitments");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Repayments");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Trust");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Deadlines");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton7.setText("Borrowers in Athens");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tables");

        jLabel3.setText("Views");

        jButton8.setText("Borrowers' Stats");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Disconnected");

        jLabel5.setFont(new java.awt.Font("Curlz MT", 1, 11)); // NOI18N
        jLabel5.setText("TBK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Query10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Query2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(query6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Lenders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Borrowers, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Inter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(243, 243, 243))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ConnectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(152, 152, 152))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(225, 225, 225))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(query6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Query8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lenders)
                                    .addComponent(Borrowers))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inter_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Query9)
                    .addComponent(ConnectBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Query10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnActionPerformed
        
        JOptionPane.showMessageDialog(null,
    "Trying to connect");
         ConnEst con=new ConnEst();
        connDB= con.estcon();
        if(connDB!=null) {
            JOptionPane.showMessageDialog(null,
    "Connected");
            jLabel4.setText("Connected");
            jLabel4.setForeground(Color.green);
            
        }
        else {JOptionPane.showMessageDialog(null,
    "Connection Failed");}
    }//GEN-LAST:event_ConnectBtnActionPerformed

    private void BorrowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowersActionPerformed
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Borrowers");
        }
        catch(SQLException sqle){}
    }//GEN-LAST:event_BorrowersActionPerformed

    private void LendersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LendersActionPerformed
       
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Lenders");
        }
        catch(SQLException sqle){}
    }//GEN-LAST:event_LendersActionPerformed

    private void Inter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inter_btnActionPerformed
       
        try{
        table_options to=new table_options(null,null);
       to.main(connDB,"Intermediaries");
        }
        catch(SQLException sqle){}
    }//GEN-LAST:event_Inter_btnActionPerformed

    private void Query2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query2ActionPerformed
        // TODO add your handling code here:
        String query=new String("select l.Id,ISNULL(sum(Re.Amount),0) as Amount_paid,max(lr.Amount) as Amount_requested,ISNULL(max(lr.Amount),0)- ISNULL(sum(Re.Amount),0) as Balance\n" +
"                              from  Loans as l \n" +
"							  join LoanRequests as lr on l.b_id=lr.b_id and l.DateOfRequest=lr.DateOfRequest  left join \n" +
"							  Repayments as Re on Re.Id=l.Id\n" +
"\n" +
"							  group by l.Id");
        
         Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
        //query_maker(query); 
    }//GEN-LAST:event_Query2ActionPerformed

    private void Query3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query3ActionPerformed
         String query=new String("select Lid,max(Name) as Name,count(Lid) as Commitments "+
		  "from "+ 
        " (select c.l_id as Lid, c.b_id,c.DateOfRequest,c.Amount as Amount_Offered,l.Name as Name "+
             "from (Commitments as c inner join Lenders as l on l.l_id=c.l_id )"+  
                  " ) as l5 "+
			 "join LoanRequests as lr on lr.b_id=l5.b_id and lr.DateOfRequest=l5.DateOfRequest "+
          "where Amount_Offered>(Amount/2) "+
          "group by Lid");
         Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
        
        
        
    }//GEN-LAST:event_Query3ActionPerformed

    private void Query1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query1ActionPerformed
        String query=new String("select name,avg_trust from Borrowers join(select b_id,avg(Percentage) as avg_trust"+
                                "  from Trust group by b_id) as L1 on L1.b_id=Borrowers.b_id");
         Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
      
    }//GEN-LAST:event_Query1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Deadlines");
        }
        catch(SQLException sqle)
        {
            JOptionPane.showMessageDialog(null,sqle+"");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"LoanRequests");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Commitments");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Loans");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Repayments");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Trust");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Query4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query4ActionPerformed
        // TODO add your handling code here:
        String query=new String("select Id as Loan_id,count(distinct l_id)as Lenders "+
"from Commitments join Loans on (Commitments.b_id=Loans.b_id and Commitments.DateOfRequest=Loans.DateOfRequest) "+
"group by Id ");
         Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query4ActionPerformed

    private void Query5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query5ActionPerformed
         String query=new String("select Id as Loan_Id,DATEADD(day,PaybackPeriod,Deadline) as Deadline,Amount "+
"from Loans join LoanRequests on Loans.b_id=LoanRequests.b_id " +
"and Loans.DateOfRequest=LoanRequests.DateOfRequest "+
"where (DATEADD(day,PaybackPeriod,Deadline)<getDate()) ");
          Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query5ActionPerformed

    private void query6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query6ActionPerformed
        // TODO add your handling code here:
        
String query=new String("select Loan_ID,sum(amount_paid) as Amount_paid "+
"from (select Loans.Id as Loan_ID,Amount as amount_paid,b_id,DateOfRequest from Repayments "+ 
"join Loans on Loans.Id=Repayments.Id) as l5 "+
"join LoanRequests on LoanRequests.b_id=l5.b_id and LoanRequests.DateOfRequest=l5.DateOfRequest "+
"group by Loan_ID,Amount "+
"having sum(amount_paid)=Amount ");
  Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_query6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Borrowers_Athens");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         try{
        table_options to=new table_options(null,null);
        to.main(connDB,"Borrowers_Stats");
        }
        catch(SQLException sqle){
        JOptionPane.showMessageDialog(null,sqle+"");}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Query7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query7ActionPerformed
        String query=new String("select b.b_id as b_id,max(b.name) as Name,sum(amount_req) as Amount_Requested "+
"from Borrowers as b join Loans as l on l.b_id=b.b_id join "+
" (select b_id,Amount as amount_req,DateOfRequest from LoanRequests) " +
" as l5 on l5.b_id=b.b_id and l.DateOfRequest=l5.DateOfRequest " +
"group by b.b_id "+
"having sum(amount_req)>=10000 "+
 "order by Amount_Requested desc "               );
  Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query7ActionPerformed

    private void Query8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query8ActionPerformed
       String query=new String("select b.b_id as b_id,b.name as Name,DateOfApproval,Amount\n" +
"from Borrowers as b join Loans as l on l.b_id=b.b_id join (select b_id,Amount,DateOfRequest,Description from LoanRequests) as l5 on l5.b_id=b.b_id and l.DateOfRequest=l5.DateOfRequest\n" +
"where Description like '%ortgage%' ");
  Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query8ActionPerformed

    private void Query10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query10ActionPerformed
         String query=new String("select lr.b_id,lr.DateOfRequest,max(lr.Amount)-ISNULL(sum(c.Amount),0) as Balance\n" +
"from LoanRequests as lr left join Commitments as c on c.b_id=lr.b_id and c.DateOfRequest=lr.DateOfRequest\n" +
"\n" +
"group by lr.b_id,lr.DateOfRequest,lr.Amount\n");
  Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query10ActionPerformed

    private void Query9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query9ActionPerformed
        String query=new String("select b_id,DateOfRequest,Deadline\n" +
"from LoanRequests\n" +
"where Deadline<getdate()");
  Query_form query_form=new Query_form(null,null);
         query_form.main(query,connDB);
    }//GEN-LAST:event_Query9ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectionDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectionDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectionDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectionDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectionDB().setVisible(true);
            }
        });
    }

    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
     public void query_maker(String query_st)
     {
           if(connDB!=null){
        try
        {
            Statement stmt=connDB.createStatement();
            ResultSet rset= stmt.executeQuery(query_st);
            JTable table=new JTable(buildTableModel(rset));
            JOptionPane.showMessageDialog(null,new JScrollPane(table)); 
        }
        catch(SQLException sqle)
        {
            JOptionPane.showMessageDialog(null,sqle);     
        }
        
           }
        else {
                JOptionPane.showMessageDialog(null,"No connection established");
           }
        
      
      
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrowers;
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JButton Inter_btn;
    private javax.swing.JButton Lenders;
    private javax.swing.JButton Query1;
    private javax.swing.JButton Query10;
    private javax.swing.JButton Query2;
    private javax.swing.JButton Query3;
    private javax.swing.JButton Query4;
    private javax.swing.JButton Query5;
    private javax.swing.JButton Query7;
    private javax.swing.JButton Query8;
    private javax.swing.JButton Query9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton query6;
    // End of variables declaration//GEN-END:variables
}
